apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vzrk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vzrk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0073-app
  name: devfile-sample-vzrk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vzrk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vzrk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0073-tenant/tkrw-pr712-0075-0073-app/devfile-sample-vzrk@sha256:2a084f1e3b30a4389fef7ed1f4186b83fffc21368bbefbd4bed0a352dfa7ab9d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
